[theme]
base="light"
primaryColor="#8523F5"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

[theme.button]
backgroundColor="#8523F5"
textColor="#FFFFFF"
hoverColor="#F15A24" 
